### ISSUE TITLE
Route integration

### ISSUE THREAD

**Issue by manishapriya94** [OpenSourceFellows/amplify#145]
![Image](https://github.com/ProgramEquity/amplify/assets/9143339/82ec68b7-b9aa-4cb8-87a6-897d85efe1fb)

This is one of the tasks of [Configuring Twilio for SMS](https://github.com/ProgramEquity/amplify/issues/128)

TWILIO_SECRET_KEY needs to be configured in routes within 
- [ ] Uncomment and npm install twilio in [api.js](https://github.com/ProgramEquity/amplify/blob/main/server/api.js)
<img width="711" alt="Screen Shot 2022-03-23 at 8 42 52 AM" src="https://user-images.githubusercontent.com/9143339/159739085-6ea4e1ff-9a49-4517-8ce1-1b6390b33af6.png">

- [ ] In [twilio.js](https://github.com/ProgramEquity/amplify/blob/main/server/routes/api/twilio.js), uncomment and configure client side 
<img width="954" alt="Screen Shot 2022-03-23 at 8 36 35 AM" src="https://user-images.githubusercontent.com/9143339/159738017-d36a9d24-56d6-4bc7-aa70-72f147d70e5e.png">

**Comment by davidchapuis** [comment]
Hi folks, I had a look at the issue and could solve it on my branch.

**Comment by manishapriya94** [comment]
In contributing.md, you can add: 

Setting up Twilio API locally. 
1. Change the secret token to 
2. Set up account ID 
Go to the Twilio website ([https://www.twilio.com/](vscode-file://vscode-app/private/var/folders/r0/dbll833s1gdbn_j_fdd099fh0000gn/T/AppTranslocation/83FBA0A1-1AED-4760-9426-6DDC9CDA4461/d/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)) and click on the "Sign Up" button in the top right corner.

Follow the prompts to create a new account. You will need to provide your email address, phone number, and a password.

Once you have created your account, you will be taken to the Twilio Console. Click on the "Create a Project" button to create a new project.

Follow the prompts to create a new project. You will need to provide a name for your project and select the type of project you want to create (e.g. SMS, Voice, etc.).

Once you have created your project, you will be taken to the project dashboard. Here you will find your Account SID, which is a unique identifier for your Twilio account.

You can use this Account SID to authenticate your requests to the Twilio API. You will also need to generate an API key and secret to use with the Twilio API. You can do this by going to the "API Keys" section of the Twilio Console and clicking on the "Create API Key" button.

Follow the prompts to create a new API key. You will need to provide a friendly name for your API key and select the permissions you want to grant to the key.

Once you have created your API key, you will be given an API key SID and secret. You can use these values to authenticate your requests to the Twilio API.

Note that you will need to keep your Account SID and API key secret, as they are used to authenticate your requests to the Twilio API.

**Comment by davidchapuis** [comment]
Solved in #850

**Comment by cisdell** [comment]
can I be unsub’ed from this?
